//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppli_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appliWebLogsEntities1 : DbContext
    {
        public appliWebLogsEntities1()
            : base("name=appliWebLogsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anomalie> anomalie { get; set; }
        public virtual DbSet<batch> batch { get; set; }
        public virtual DbSet<corbeille> corbeille { get; set; }
        public virtual DbSet<domaine> domaine { get; set; }
        public virtual DbSet<log> log { get; set; }
        public virtual DbSet<messageErreur> messageErreur { get; set; }
        public virtual DbSet<pole> pole { get; set; }
        public virtual DbSet<serveur> serveur { get; set; }
        public virtual DbSet<severite> severite { get; set; }
        public virtual DbSet<statut> statut { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<type> type { get; set; }
        public virtual DbSet<utilisateur> utilisateur { get; set; }
        public virtual DbSet<corbeillePersonnelle> corbeillePersonnelle { get; set; }
    }
}
