//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppli_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public log()
        {
            this.anomalie = new HashSet<anomalie>();
        }
    
        public int identifiant { get; set; }
        public string nom { get; set; }
        public string domaine { get; set; }
        public string titre { get; set; }
        public string numeroEtape { get; set; }
        public string pole { get; set; }
        public string horodatage { get; set; }
        public System.DateTime dateCreation { get; set; }
        public string nomServeur { get; set; }
        public string adresseServeur { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anomalie> anomalie { get; set; }
    }
}
