//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppli_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrageAnomalie
    {
        public int identifiant { get; set; }
        public string severite { get; set; }
        public string type { get; set; }
        public string messageErreur { get; set; }
        public string phraseExclue { get; set; }
        public string statut { get; set; }
    }
}
