//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetAppli_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrageLogs
    {
        public string libelleServeur { get; set; }
        public string cheminServeur { get; set; }
        public string libelleBatch { get; set; }
        public int identifiantLog { get; set; }
        public string identifiantDomaine { get; set; }
        public string libelleDomaine { get; set; }
        public string identifiantPole { get; set; }
        public string libellePole { get; set; }
    }
}
